// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgL7OLuIXvF-85PRbECSjwZ1hiquZebNU',
    appId: '1:734513705676:web:649302108f1a225f284869',
    messagingSenderId: '734513705676',
    projectId: 'is381-2024-final',
    authDomain: 'is381-2024-final.firebaseapp.com',
    storageBucket: 'is381-2024-final.firebasestorage.app',
    measurementId: 'G-564NXPKSH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-qWGH88iIEmTLObE-T8y-9uXGC1leRhw',
    appId: '1:734513705676:android:31a76e49573142c6284869',
    messagingSenderId: '734513705676',
    projectId: 'is381-2024-final',
    storageBucket: 'is381-2024-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXL402q0woVl-Jc8LSExBRSzAU8rWpYr4',
    appId: '1:734513705676:ios:ac1819f02737b5ae284869',
    messagingSenderId: '734513705676',
    projectId: 'is381-2024-final',
    storageBucket: 'is381-2024-final.firebasestorage.app',
    iosBundleId: 'com.example.patcharaphornFinalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXL402q0woVl-Jc8LSExBRSzAU8rWpYr4',
    appId: '1:734513705676:ios:ac1819f02737b5ae284869',
    messagingSenderId: '734513705676',
    projectId: 'is381-2024-final',
    storageBucket: 'is381-2024-final.firebasestorage.app',
    iosBundleId: 'com.example.patcharaphornFinalApp',
  );
}
